### PR TITLE
Revival

### PR DESCRIPTION
**Pull request by Firtzberg**
The code here is good.
I dislike the package using the deprecated interop package. That makes is deprecated. I changed it to use PSR as suggested by the interop package itself.
I upgraded PHPUnit and code coverage package. I use mocks instead of Picotainer.

I intend to add more tests if you agree with the changes so far.

### CODE REVIEW

**Comment by moufmouf** [comment]
Excellent, I'll create a new 2.0 branch (since targetting PSR-11 directly is a breaking change)

**Comment by moufmouf** [comment]
I think the Travis file needs some love too :)
You can upgrade it to only support recent PHP versions if you want.

**Comment by Firtzberg** [comment]
> I think the Travis file needs some love too :)
> You can upgrade it to only support recent PHP versions if you want.

I'll try. Thank you for the quick reply.

**Comment by Firtzberg** [comment]
I'll make another PR to the new branch.
Just let me see how my latest changes affect CI results.

**Comment by moufmouf** [comment]
> I'll make another PR to the new branch.

No need, I changed the targeted branch in this PR.

**Comment by Firtzberg** [comment]
OK, I don't know why the interface doesn't get found when tarvis runs the tests.
I am able to run the tests and interpret the code coverage report on my local machine.
I would appreciate help with the tarvis file.

**Comment by Firtzberg** [comment]
I reduced the number of commits, we're good to go now.
I'll have 3 more PRs after this is merged.

**Comment by Firtzberg** [comment]
Sorry to bother, but can we move this forward?
I need this by Monday.

**Comment by moufmouf** [comment]
Excellent! Thanks a lot!

**Pull request merged**
