### PR TITLE
PHP code sniffer

### PR DESCRIPTION
**Pull request by Firtzberg**
Added spell checker (PHP code sniffer) and complying with PSR-2.

### CODE REVIEW

**Comment by Firtzberg** [comment]
After the two PRs get merged please make a new release with the major version being 2.

**Comment by Firtzberg** [comment]
@moufmouf Where are we with this?
I need this for a package which I developed.

**Comment by Firtzberg** [comment]
@moufmouf 
Sorry to be a pain in the ass. I would like this merged and released so that I can use it in another package.
If it doesn't happen within this week I intend to release this package under my own name.
I hope that's fine with you.

**Comment by moufmouf** [comment]
Hey @Fritzberg,

I'm sorry, I completely missed your last 2 PRs.

You know what? You probably have invested more time in this project than I have and you definitely seem to know what you are doing. I have a ton of other projects to manage so I keep missing your notifications.

I'll add you as a maintainer on this repository. Simply notify me when you are doing changes and if you don't hear for me in the coming days, assume I'm ok :D

**Pull request merged**
